name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  actions: write

jobs:
  deploy-to-github-pages:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4


      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './app/frontend/package-lock.json'

      - name: Install dependencies
        working-directory: ./app/frontend
        run: npm ci

      - name: Build for GitHub Pages
        working-directory: ./app/frontend
        run: npm run build
        env:
          NEXT_PUBLIC_DEPLOY_SOURCE: 'github-pages'

      - name: Add .nojekyll file
        working-directory: ./app/frontend
        run: |
          mkdir -p out
          touch out/.nojekyll

      - name: Add CNAME file
        working-directory: ./app/frontend
        run: echo "devops5.himanmanduja.fun" > out/CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./app/frontend/out
          publish_branch: gh-pages
          force_orphan: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          cname: devops5.himanmanduja.fun
